### PR TITLE
Update to target .Net Standard 2.0

### PR DESCRIPTION
**Pull request by frenkan**
Update to taget .Net Standard 2.0
.cs files left as is. AssemblyInfo details are now in .csproj and updated.

Wirth noting is that the RustflakesService is removed since it doesn't play nice with .Net Standard.

### CODE REVIEW

**Comment by frenkan** [comment]
@peschkaj would it be possible to push this version to nuget?

**Comment by peschkaj** [comment]
Can do. I’ll bump the major version number as well to signify the changes.

Jeremiah Peschka

**Comment by frenkan** [comment]
Fantastic, thanks.
My PR did an update to assembly version to 2.0.0. It is now in the csproj file.

**Comment by peschkaj** [comment]
Updated package has been published and I’ve tagged the release in GitHub. Thanks for your contribution!

Jeremiah Peschka

**Pull request merged**
